# Site settings
minimal_mistakes_skin: "dirt"
locale: "en-US"

masthead_title: Songpoem Labs
title: Songpoem Solutions LLP
email: sandesh.soni@songpoem.com
description: >- # this means to ignore newlines until "baseurl:"
  Lets Compose Success Together.
logo: "/assets/images/songpoemlabs-logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.songpoem.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: songpoemlabs
github_username: songpoemlabs
facebook_username: songpoemlabs

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /blog/:categories/:slug/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _posts/*/*
  - _pages
  - _services

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-postcss

postcss:
  cache: false

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/songpoemlabs"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-li-square"
      url: "https://linkedin.com/company/songpoemlabs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/songpoemlabs"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/songpoemlabs"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: false
  - scope:
      path: "_services"
      type: service
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google"
  google:
    tracking_id: "G-GTYGD0GH2H"
    anonymize_ip: true
